name: Jobdirecto
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
    build:
        # Job name is Greeting
        name: ESLint
        # This job runs on Linux
        runs-on: ubuntu-latest
        steps:
            - name: ESLint checks
              uses: gimenete/eslint-action@1.0
